name: iOS SDK Build and Lint

on: [pull_request]

env:
  XCODE_VERSION: "26.2"

jobs:
  pod-lint:
    runs-on: macOS-15
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Update xcodeproj gem
        run: sudo gem install xcodeproj

      - name: Prevent social URL warnings if twitter is unreachable
        run: find . -path '*.podspec' -exec perl -pi -e 's/.+\.social_media_url.+//' {} \;

      - name: Lint with CocoaPods
        run: pod lib lint

      - name: Undo twitter change to podspec
        run: git checkout *.podspec

  xcode-build:
    runs-on: macOS-15
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Build SDK
        run: |
          set -o pipefail
          xcodebuild -resolvePackageDependencies \
            -project "mParticle-Apple-Media-SDK.xcodeproj" \
            -scheme "mParticle-Apple-Media-SDK" \
            -destination "generic/platform=iOS" \
            clean build | xcpretty

  run-analyzer:
    runs-on: macOS-15
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Run static analyzer
        run: |
          bash -c '! (set -o pipefail && xcodebuild -project "mParticle-Apple-Media-SDK.xcodeproj" -scheme "mParticle-Apple-Media-SDK" -sdk iphonesimulator -configuration Debug -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" clean analyze | grep -v "warning: The iOS Simulator deployment target" | grep -B3 "warning")'
